FROM rust:1-bookworm AS builder

WORKDIR /home/workspace

RUN rustup default nightly 
RUN rustup target add wasm32-unknown-unknown wasm32-wasi

FROM builder AS development
RUN curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && mv spin /usr/local/bin/
RUN cargo install --locked trunk 
RUN cargo install leptosfmt

EXPOSE 3000

CMD ["sleep", "infinity"]
