FROM rust:1-bookworm AS builder

WORKDIR /home/workspace

RUN rustup default nightly 
RUN rustup target add wasm32-unknown-unknown

RUN cargo install --locked cargo-leptos

FROM builder AS development
RUN cargo install --locked trunk 
RUN cargo install leptosfmt
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t robbyrussell \
    -p git \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions

EXPOSE 3000

CMD ["sleep", "infinity"]
