[package]
name = "api"
authors = ["Diversable <dan.mantei@outlook.com>"]
description = "api for Leptos CSR examples"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v2.1.0" }

[workspace]
